---
- include: deploy_monitors.yml

- include: start_monitor.yml

- include: ceph_keys.yml
  # this avoids the bug mentioned here: https://github.com/ansible/ansible/issues/18206
  static: no

- include: create_mds_filesystems.yml
  when:
    - groups[mds_group_name] is defined
    - "{{ groups[mds_group_name]|length > 0 }}"

- include: secure_cluster.yml
  when:
    - secure_cluster

- include: ./docker/main.yml

- include: calamari.yml
  when: calamari
